### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by werdnum** [printpal-io/PrintWatch#1]
I previously cancelled my subscription because the plugin put unacceptable load on Octoprint. I'm now trying something different - pulling webcam feeds from the Octoprint instance remotely and sending them to PrintPal with a custom plugin integration.

To do this, I modified the example slightly to send the image from a remote Octoprint instance:

```python
import argparse
import logging
import os
import printwatch.client
import requests
import time

argparser = argparse.ArgumentParser(description='When pointed at a remote OctoPrint instance, sends images to PrintPal.IO for analysis.')
argparser.add_argument('webcam_url', metavar='O', type=str, help='URL of the webcam feed - e.g. http://127.0.0.1/webcam/stream')
argparser.add_argument('--interval', default=30, type=int, help='Request an image and run it through PrintPal every this many seconds.')
argparser.add_argument('--api-key', default=os.getenv('PRINTWATCH_API_KEY'), help='API Key to use (defaults to $PRINTWATCH_API_KEY)')

args = argparser.parse_args()

client = printwatch.client.PrintWatchClient()

logging.basicConfig(level='INFO')
logger = logging.getLogger(__name__)

is_first = True
while True:
    if not is_first:
        time.sleep(args.interval)
    is_first = False
    r = requests.get(args.webcam_url)
    if r.status_code != 200:
        logger.warning("Error %d retrieving webcam stream: %s", r.status_code, r.text)
        continue
    if r.headers['content-type'] != 'image/jpeg':
        logger.warning("Data is of type %s, expected image/jpeg", r.headers['content-type'])
        continue
    results = client.send_infer(r.content, args.api_key)
    logger.info("Got result: %s", results)
```

When I run it, the result I get is:

```
INFO:__main__:Got result: {'actionType': 'none', 'response': 'Settings check failed', 'statusCode': 212}
```

This is described in the [documentation](https://printpal.io/documentation/api/) as "Either the API key is not valid, the printer is in use already, or you are making calls too frequently."

but none of these should be the case - I note that the [library sets the printer ID to a random string](https://github.com/printpal-io/PrintWatch/blob/main/printwatch/client.py#L37), so that shouldn't be a problem (unless maybe the issue is my API key is only valid for 1 printer?), and I'm sending a request every 30 seconds, which should be fine. When I use an invalid API key, I get an error message that tells me so.

Maybe something to do with the fact that I cancelled and then re-subscribed and it's put me back in the trial group?

Either way, I need a clear error message to find out what precisely is wrong - it's not really much fun to get a generic error message that could have 3 or 4 different causes and have to guess which one is applicable.

**Comment by printpal-io** [comment]
> I previously cancelled my subscription because the plugin put unacceptable load on Octoprint. I'm now trying something different - pulling webcam feeds from the Octoprint instance remotely and sending them to PrintPal with a custom plugin integration.
> 
> To do this, I modified the example slightly to send the image from a remote Octoprint instance:
> 
> ```python
> import argparse
> import logging
> import os
> import printwatch.client
> import requests
> import time
> 
> argparser = argparse.ArgumentParser(description='When pointed at a remote OctoPrint instance, sends images to PrintPal.IO for analysis.')
> argparser.add_argument('webcam_url', metavar='O', type=str, help='URL of the webcam feed - e.g. http://127.0.0.1/webcam/stream')
> argparser.add_argument('--interval', default=30, type=int, help='Request an image and run it through PrintPal every this many seconds.')
> argparser.add_argument('--api-key', default=os.getenv('PRINTWATCH_API_KEY'), help='API Key to use (defaults to $PRINTWATCH_API_KEY)')
> 
> args = argparser.parse_args()
> 
> client = printwatch.client.PrintWatchClient()
> 
> logging.basicConfig(level='INFO')
> logger = logging.getLogger(__name__)
> 
> is_first = True
> while True:
>     if not is_first:
>         time.sleep(args.interval)
>     is_first = False
>     r = requests.get(args.webcam_url)
>     if r.status_code != 200:
>         logger.warning("Error %d retrieving webcam stream: %s", r.status_code, r.text)
>         continue
>     if r.headers['content-type'] != 'image/jpeg':
>         logger.warning("Data is of type %s, expected image/jpeg", r.headers['content-type'])
>         continue
>     results = client.send_infer(r.content, args.api_key)
>     logger.info("Got result: %s", results)
> ```
> 
> When I run it, the result I get is:
> 
> ```
> INFO:__main__:Got result: {'actionType': 'none', 'response': 'Settings check failed', 'statusCode': 212}
> ```
> 
> This is described in the [documentation](https://printpal.io/documentation/api/) as "Either the API key is not valid, the printer is in use already, or you are making calls too frequently."
> 
> but none of these should be the case - I note that the [library sets the printer ID to a random string](https://github.com/printpal-io/PrintWatch/blob/main/printwatch/client.py#L37), so that shouldn't be a problem (unless maybe the issue is my API key is only valid for 1 printer?), and I'm sending a request every 30 seconds, which should be fine. When I use an invalid API key, I get an error message that tells me so.
> 
> Maybe something to do with the fact that I cancelled and then re-subscribed and it's put me back in the trial group?
> 
> Either way, I need a clear error message to find out what precisely is wrong - it's not really much fun to get a generic error message that could have 3 or 4 different causes and have to guess which one is applicable.

The cpu load issue has been brought to our attention today and we are adding it to the client plugin update scheduled for tomorrow. It should now run at ~3% cpu load. 

We purposefully obfuscate some of the server responses to protect our code. I will take a look at this for you via email.

**Comment by printpal-io** [comment]
Issue resolved.
